ERROR - 2021-10-14 12:41:21 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-10-14 12:41:21 --> Unable to connect to the database.
#0 /opt/lampp/htdocs/inventario/system/Session/Handlers/DatabaseHandler.php(115): CodeIgniter\Database\BaseConnection->initialize()
#1 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#2 /opt/lampp/htdocs/inventario/system/Session/Session.php(1027): session_start()
#3 /opt/lampp/htdocs/inventario/system/Session/Session.php(226): CodeIgniter\Session\Session->startSession()
#4 /opt/lampp/htdocs/inventario/system/Config/Services.php(714): CodeIgniter\Session\Session->start()
#5 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(100): CodeIgniter\Config\Services::session(Object(Config\App), false)
#6 /opt/lampp/htdocs/inventario/system/Config/Services.php(699): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#7 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(171): CodeIgniter\Config\Services::session()
#8 /opt/lampp/htdocs/inventario/system/Common.php(999): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 /opt/lampp/htdocs/inventario/app/Filters/AuthCheckFilter.php(13): session()
#10 /opt/lampp/htdocs/inventario/system/Filters/Filters.php(181): App\Filters\AuthCheckFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#11 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(403): CodeIgniter\Filters\Filters->run('/', 'before')
#12 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2021-10-14 12:43:19 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-10-14 12:43:19 --> Unable to connect to the database.
#0 /opt/lampp/htdocs/inventario/system/Session/Handlers/DatabaseHandler.php(115): CodeIgniter\Database\BaseConnection->initialize()
#1 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#2 /opt/lampp/htdocs/inventario/system/Session/Session.php(1027): session_start()
#3 /opt/lampp/htdocs/inventario/system/Session/Session.php(226): CodeIgniter\Session\Session->startSession()
#4 /opt/lampp/htdocs/inventario/system/Config/Services.php(714): CodeIgniter\Session\Session->start()
#5 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(100): CodeIgniter\Config\Services::session(Object(Config\App), false)
#6 /opt/lampp/htdocs/inventario/system/Config/Services.php(699): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#7 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(171): CodeIgniter\Config\Services::session()
#8 /opt/lampp/htdocs/inventario/system/Common.php(999): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 /opt/lampp/htdocs/inventario/app/Filters/AuthCheckFilter.php(13): session()
#10 /opt/lampp/htdocs/inventario/system/Filters/Filters.php(181): App\Filters\AuthCheckFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#11 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(403): CodeIgniter\Filters\Filters->run('/', 'before')
#12 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2021-10-14 12:43:25 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-10-14 12:43:25 --> Unable to connect to the database.
#0 /opt/lampp/htdocs/inventario/system/Session/Handlers/DatabaseHandler.php(115): CodeIgniter\Database\BaseConnection->initialize()
#1 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#2 /opt/lampp/htdocs/inventario/system/Session/Session.php(1027): session_start()
#3 /opt/lampp/htdocs/inventario/system/Session/Session.php(226): CodeIgniter\Session\Session->startSession()
#4 /opt/lampp/htdocs/inventario/system/Config/Services.php(714): CodeIgniter\Session\Session->start()
#5 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(100): CodeIgniter\Config\Services::session(Object(Config\App), false)
#6 /opt/lampp/htdocs/inventario/system/Config/Services.php(699): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#7 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(171): CodeIgniter\Config\Services::session()
#8 /opt/lampp/htdocs/inventario/system/Common.php(999): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 /opt/lampp/htdocs/inventario/app/Filters/AuthCheckFilter.php(13): session()
#10 /opt/lampp/htdocs/inventario/system/Filters/Filters.php(181): App\Filters\AuthCheckFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#11 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(403): CodeIgniter\Filters\Filters->run('/', 'before')
#12 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2021-10-14 12:43:30 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-10-14 12:43:30 --> Unable to connect to the database.
#0 /opt/lampp/htdocs/inventario/system/Session/Handlers/DatabaseHandler.php(115): CodeIgniter\Database\BaseConnection->initialize()
#1 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#2 /opt/lampp/htdocs/inventario/system/Session/Session.php(1027): session_start()
#3 /opt/lampp/htdocs/inventario/system/Session/Session.php(226): CodeIgniter\Session\Session->startSession()
#4 /opt/lampp/htdocs/inventario/system/Config/Services.php(714): CodeIgniter\Session\Session->start()
#5 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(100): CodeIgniter\Config\Services::session(Object(Config\App), false)
#6 /opt/lampp/htdocs/inventario/system/Config/Services.php(699): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#7 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(171): CodeIgniter\Config\Services::session()
#8 /opt/lampp/htdocs/inventario/system/Common.php(999): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 /opt/lampp/htdocs/inventario/app/Filters/AuthCheckFilter.php(13): session()
#10 /opt/lampp/htdocs/inventario/system/Filters/Filters.php(181): App\Filters\AuthCheckFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#11 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(403): CodeIgniter\Filters\Filters->run('/crud', 'before')
#12 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2021-10-14 12:43:32 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-10-14 12:43:32 --> Unable to connect to the database.
#0 /opt/lampp/htdocs/inventario/system/Session/Handlers/DatabaseHandler.php(115): CodeIgniter\Database\BaseConnection->initialize()
#1 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#2 /opt/lampp/htdocs/inventario/system/Session/Session.php(1027): session_start()
#3 /opt/lampp/htdocs/inventario/system/Session/Session.php(226): CodeIgniter\Session\Session->startSession()
#4 /opt/lampp/htdocs/inventario/system/Config/Services.php(714): CodeIgniter\Session\Session->start()
#5 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(100): CodeIgniter\Config\Services::session(Object(Config\App), false)
#6 /opt/lampp/htdocs/inventario/system/Config/Services.php(699): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#7 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(171): CodeIgniter\Config\Services::session()
#8 /opt/lampp/htdocs/inventario/system/Common.php(999): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 /opt/lampp/htdocs/inventario/app/Filters/AuthCheckFilter.php(13): session()
#10 /opt/lampp/htdocs/inventario/system/Filters/Filters.php(181): App\Filters\AuthCheckFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#11 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(403): CodeIgniter\Filters\Filters->run('/', 'before')
#12 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2021-10-14 12:44:53 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-10-14 12:44:53 --> Unable to connect to the database.
#0 /opt/lampp/htdocs/inventario/system/Session/Handlers/DatabaseHandler.php(115): CodeIgniter\Database\BaseConnection->initialize()
#1 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#2 /opt/lampp/htdocs/inventario/system/Session/Session.php(1027): session_start()
#3 /opt/lampp/htdocs/inventario/system/Session/Session.php(226): CodeIgniter\Session\Session->startSession()
#4 /opt/lampp/htdocs/inventario/system/Config/Services.php(714): CodeIgniter\Session\Session->start()
#5 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(100): CodeIgniter\Config\Services::session(Object(Config\App), false)
#6 /opt/lampp/htdocs/inventario/system/Config/Services.php(699): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#7 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(171): CodeIgniter\Config\Services::session()
#8 /opt/lampp/htdocs/inventario/system/Common.php(999): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 /opt/lampp/htdocs/inventario/app/Filters/AuthCheckFilter.php(13): session()
#10 /opt/lampp/htdocs/inventario/system/Filters/Filters.php(181): App\Filters\AuthCheckFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#11 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(403): CodeIgniter\Filters\Filters->run('/', 'before')
#12 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2021-10-14 12:44:53 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-10-14 12:44:53 --> Unable to connect to the database.
#0 /opt/lampp/htdocs/inventario/system/Session/Handlers/DatabaseHandler.php(115): CodeIgniter\Database\BaseConnection->initialize()
#1 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#2 /opt/lampp/htdocs/inventario/system/Session/Session.php(1027): session_start()
#3 /opt/lampp/htdocs/inventario/system/Session/Session.php(226): CodeIgniter\Session\Session->startSession()
#4 /opt/lampp/htdocs/inventario/system/Config/Services.php(714): CodeIgniter\Session\Session->start()
#5 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(100): CodeIgniter\Config\Services::session(Object(Config\App), false)
#6 /opt/lampp/htdocs/inventario/system/Config/Services.php(699): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#7 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(171): CodeIgniter\Config\Services::session()
#8 /opt/lampp/htdocs/inventario/system/Common.php(999): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 /opt/lampp/htdocs/inventario/app/Filters/AuthCheckFilter.php(13): session()
#10 /opt/lampp/htdocs/inventario/system/Filters/Filters.php(181): App\Filters\AuthCheckFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#11 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(403): CodeIgniter\Filters\Filters->run('/', 'before')
#12 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2021-10-14 12:44:54 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-10-14 12:44:54 --> Unable to connect to the database.
#0 /opt/lampp/htdocs/inventario/system/Session/Handlers/DatabaseHandler.php(115): CodeIgniter\Database\BaseConnection->initialize()
#1 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#2 /opt/lampp/htdocs/inventario/system/Session/Session.php(1027): session_start()
#3 /opt/lampp/htdocs/inventario/system/Session/Session.php(226): CodeIgniter\Session\Session->startSession()
#4 /opt/lampp/htdocs/inventario/system/Config/Services.php(714): CodeIgniter\Session\Session->start()
#5 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(100): CodeIgniter\Config\Services::session(Object(Config\App), false)
#6 /opt/lampp/htdocs/inventario/system/Config/Services.php(699): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#7 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(171): CodeIgniter\Config\Services::session()
#8 /opt/lampp/htdocs/inventario/system/Common.php(999): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 /opt/lampp/htdocs/inventario/app/Filters/AuthCheckFilter.php(13): session()
#10 /opt/lampp/htdocs/inventario/system/Filters/Filters.php(181): App\Filters\AuthCheckFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#11 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(403): CodeIgniter\Filters\Filters->run('/', 'before')
#12 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2021-10-14 12:44:54 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-10-14 12:44:54 --> Unable to connect to the database.
#0 /opt/lampp/htdocs/inventario/system/Session/Handlers/DatabaseHandler.php(115): CodeIgniter\Database\BaseConnection->initialize()
#1 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#2 /opt/lampp/htdocs/inventario/system/Session/Session.php(1027): session_start()
#3 /opt/lampp/htdocs/inventario/system/Session/Session.php(226): CodeIgniter\Session\Session->startSession()
#4 /opt/lampp/htdocs/inventario/system/Config/Services.php(714): CodeIgniter\Session\Session->start()
#5 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(100): CodeIgniter\Config\Services::session(Object(Config\App), false)
#6 /opt/lampp/htdocs/inventario/system/Config/Services.php(699): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#7 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(171): CodeIgniter\Config\Services::session()
#8 /opt/lampp/htdocs/inventario/system/Common.php(999): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 /opt/lampp/htdocs/inventario/app/Filters/AuthCheckFilter.php(13): session()
#10 /opt/lampp/htdocs/inventario/system/Filters/Filters.php(181): App\Filters\AuthCheckFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#11 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(403): CodeIgniter\Filters\Filters->run('/', 'before')
#12 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2021-10-14 12:44:54 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-10-14 12:44:54 --> Unable to connect to the database.
#0 /opt/lampp/htdocs/inventario/system/Session/Handlers/DatabaseHandler.php(115): CodeIgniter\Database\BaseConnection->initialize()
#1 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#2 /opt/lampp/htdocs/inventario/system/Session/Session.php(1027): session_start()
#3 /opt/lampp/htdocs/inventario/system/Session/Session.php(226): CodeIgniter\Session\Session->startSession()
#4 /opt/lampp/htdocs/inventario/system/Config/Services.php(714): CodeIgniter\Session\Session->start()
#5 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(100): CodeIgniter\Config\Services::session(Object(Config\App), false)
#6 /opt/lampp/htdocs/inventario/system/Config/Services.php(699): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#7 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(171): CodeIgniter\Config\Services::session()
#8 /opt/lampp/htdocs/inventario/system/Common.php(999): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 /opt/lampp/htdocs/inventario/app/Filters/AuthCheckFilter.php(13): session()
#10 /opt/lampp/htdocs/inventario/system/Filters/Filters.php(181): App\Filters\AuthCheckFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#11 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(403): CodeIgniter\Filters\Filters->run('/', 'before')
#12 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2021-10-14 12:44:54 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-10-14 12:44:54 --> Unable to connect to the database.
#0 /opt/lampp/htdocs/inventario/system/Session/Handlers/DatabaseHandler.php(115): CodeIgniter\Database\BaseConnection->initialize()
#1 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#2 /opt/lampp/htdocs/inventario/system/Session/Session.php(1027): session_start()
#3 /opt/lampp/htdocs/inventario/system/Session/Session.php(226): CodeIgniter\Session\Session->startSession()
#4 /opt/lampp/htdocs/inventario/system/Config/Services.php(714): CodeIgniter\Session\Session->start()
#5 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(100): CodeIgniter\Config\Services::session(Object(Config\App), false)
#6 /opt/lampp/htdocs/inventario/system/Config/Services.php(699): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#7 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(171): CodeIgniter\Config\Services::session()
#8 /opt/lampp/htdocs/inventario/system/Common.php(999): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 /opt/lampp/htdocs/inventario/app/Filters/AuthCheckFilter.php(13): session()
#10 /opt/lampp/htdocs/inventario/system/Filters/Filters.php(181): App\Filters\AuthCheckFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#11 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(403): CodeIgniter\Filters\Filters->run('/', 'before')
#12 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2021-10-14 12:44:54 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-10-14 12:44:54 --> Unable to connect to the database.
#0 /opt/lampp/htdocs/inventario/system/Session/Handlers/DatabaseHandler.php(115): CodeIgniter\Database\BaseConnection->initialize()
#1 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#2 /opt/lampp/htdocs/inventario/system/Session/Session.php(1027): session_start()
#3 /opt/lampp/htdocs/inventario/system/Session/Session.php(226): CodeIgniter\Session\Session->startSession()
#4 /opt/lampp/htdocs/inventario/system/Config/Services.php(714): CodeIgniter\Session\Session->start()
#5 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(100): CodeIgniter\Config\Services::session(Object(Config\App), false)
#6 /opt/lampp/htdocs/inventario/system/Config/Services.php(699): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#7 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(171): CodeIgniter\Config\Services::session()
#8 /opt/lampp/htdocs/inventario/system/Common.php(999): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 /opt/lampp/htdocs/inventario/app/Filters/AuthCheckFilter.php(13): session()
#10 /opt/lampp/htdocs/inventario/system/Filters/Filters.php(181): App\Filters\AuthCheckFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#11 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(403): CodeIgniter\Filters\Filters->run('/', 'before')
#12 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2021-10-14 12:44:55 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-10-14 12:44:55 --> Unable to connect to the database.
#0 /opt/lampp/htdocs/inventario/system/Session/Handlers/DatabaseHandler.php(115): CodeIgniter\Database\BaseConnection->initialize()
#1 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#2 /opt/lampp/htdocs/inventario/system/Session/Session.php(1027): session_start()
#3 /opt/lampp/htdocs/inventario/system/Session/Session.php(226): CodeIgniter\Session\Session->startSession()
#4 /opt/lampp/htdocs/inventario/system/Config/Services.php(714): CodeIgniter\Session\Session->start()
#5 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(100): CodeIgniter\Config\Services::session(Object(Config\App), false)
#6 /opt/lampp/htdocs/inventario/system/Config/Services.php(699): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#7 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(171): CodeIgniter\Config\Services::session()
#8 /opt/lampp/htdocs/inventario/system/Common.php(999): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 /opt/lampp/htdocs/inventario/app/Filters/AuthCheckFilter.php(13): session()
#10 /opt/lampp/htdocs/inventario/system/Filters/Filters.php(181): App\Filters\AuthCheckFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#11 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(403): CodeIgniter\Filters\Filters->run('/', 'before')
#12 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2021-10-14 12:44:55 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-10-14 12:44:55 --> Unable to connect to the database.
#0 /opt/lampp/htdocs/inventario/system/Session/Handlers/DatabaseHandler.php(115): CodeIgniter\Database\BaseConnection->initialize()
#1 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#2 /opt/lampp/htdocs/inventario/system/Session/Session.php(1027): session_start()
#3 /opt/lampp/htdocs/inventario/system/Session/Session.php(226): CodeIgniter\Session\Session->startSession()
#4 /opt/lampp/htdocs/inventario/system/Config/Services.php(714): CodeIgniter\Session\Session->start()
#5 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(100): CodeIgniter\Config\Services::session(Object(Config\App), false)
#6 /opt/lampp/htdocs/inventario/system/Config/Services.php(699): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#7 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(171): CodeIgniter\Config\Services::session()
#8 /opt/lampp/htdocs/inventario/system/Common.php(999): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 /opt/lampp/htdocs/inventario/app/Filters/AuthCheckFilter.php(13): session()
#10 /opt/lampp/htdocs/inventario/system/Filters/Filters.php(181): App\Filters\AuthCheckFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#11 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(403): CodeIgniter\Filters\Filters->run('/', 'before')
#12 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2021-10-14 12:44:55 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-10-14 12:44:55 --> Unable to connect to the database.
#0 /opt/lampp/htdocs/inventario/system/Session/Handlers/DatabaseHandler.php(115): CodeIgniter\Database\BaseConnection->initialize()
#1 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#2 /opt/lampp/htdocs/inventario/system/Session/Session.php(1027): session_start()
#3 /opt/lampp/htdocs/inventario/system/Session/Session.php(226): CodeIgniter\Session\Session->startSession()
#4 /opt/lampp/htdocs/inventario/system/Config/Services.php(714): CodeIgniter\Session\Session->start()
#5 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(100): CodeIgniter\Config\Services::session(Object(Config\App), false)
#6 /opt/lampp/htdocs/inventario/system/Config/Services.php(699): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#7 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(171): CodeIgniter\Config\Services::session()
#8 /opt/lampp/htdocs/inventario/system/Common.php(999): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 /opt/lampp/htdocs/inventario/app/Filters/AuthCheckFilter.php(13): session()
#10 /opt/lampp/htdocs/inventario/system/Filters/Filters.php(181): App\Filters\AuthCheckFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#11 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(403): CodeIgniter\Filters\Filters->run('/', 'before')
#12 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2021-10-14 12:45:03 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-10-14 12:45:03 --> Unable to connect to the database.
#0 /opt/lampp/htdocs/inventario/system/Session/Handlers/DatabaseHandler.php(115): CodeIgniter\Database\BaseConnection->initialize()
#1 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#2 /opt/lampp/htdocs/inventario/system/Session/Session.php(1027): session_start()
#3 /opt/lampp/htdocs/inventario/system/Session/Session.php(226): CodeIgniter\Session\Session->startSession()
#4 /opt/lampp/htdocs/inventario/system/Config/Services.php(714): CodeIgniter\Session\Session->start()
#5 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(100): CodeIgniter\Config\Services::session(Object(Config\App), false)
#6 /opt/lampp/htdocs/inventario/system/Config/Services.php(699): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#7 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(171): CodeIgniter\Config\Services::session()
#8 /opt/lampp/htdocs/inventario/system/Common.php(999): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 /opt/lampp/htdocs/inventario/app/Filters/AuthCheckFilter.php(13): session()
#10 /opt/lampp/htdocs/inventario/system/Filters/Filters.php(181): App\Filters\AuthCheckFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#11 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(403): CodeIgniter\Filters\Filters->run('/', 'before')
#12 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2021-10-14 12:45:12 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-10-14 12:45:12 --> Unable to connect to the database.
#0 /opt/lampp/htdocs/inventario/system/Session/Handlers/DatabaseHandler.php(115): CodeIgniter\Database\BaseConnection->initialize()
#1 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#2 /opt/lampp/htdocs/inventario/system/Session/Session.php(1027): session_start()
#3 /opt/lampp/htdocs/inventario/system/Session/Session.php(226): CodeIgniter\Session\Session->startSession()
#4 /opt/lampp/htdocs/inventario/system/Config/Services.php(714): CodeIgniter\Session\Session->start()
#5 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(100): CodeIgniter\Config\Services::session(Object(Config\App), false)
#6 /opt/lampp/htdocs/inventario/system/Config/Services.php(699): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#7 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(171): CodeIgniter\Config\Services::session()
#8 /opt/lampp/htdocs/inventario/system/Common.php(999): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 /opt/lampp/htdocs/inventario/app/Filters/AuthCheckFilter.php(13): session()
#10 /opt/lampp/htdocs/inventario/system/Filters/Filters.php(181): App\Filters\AuthCheckFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#11 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(403): CodeIgniter\Filters\Filters->run('/', 'before')
#12 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2021-10-14 12:45:13 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-10-14 12:45:13 --> Unable to connect to the database.
#0 /opt/lampp/htdocs/inventario/system/Session/Handlers/DatabaseHandler.php(115): CodeIgniter\Database\BaseConnection->initialize()
#1 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#2 /opt/lampp/htdocs/inventario/system/Session/Session.php(1027): session_start()
#3 /opt/lampp/htdocs/inventario/system/Session/Session.php(226): CodeIgniter\Session\Session->startSession()
#4 /opt/lampp/htdocs/inventario/system/Config/Services.php(714): CodeIgniter\Session\Session->start()
#5 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(100): CodeIgniter\Config\Services::session(Object(Config\App), false)
#6 /opt/lampp/htdocs/inventario/system/Config/Services.php(699): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#7 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(171): CodeIgniter\Config\Services::session()
#8 /opt/lampp/htdocs/inventario/system/Common.php(999): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 /opt/lampp/htdocs/inventario/app/Filters/AuthCheckFilter.php(13): session()
#10 /opt/lampp/htdocs/inventario/system/Filters/Filters.php(181): App\Filters\AuthCheckFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#11 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(403): CodeIgniter\Filters\Filters->run('/', 'before')
#12 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2021-10-14 12:45:13 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-10-14 12:45:13 --> Unable to connect to the database.
#0 /opt/lampp/htdocs/inventario/system/Session/Handlers/DatabaseHandler.php(115): CodeIgniter\Database\BaseConnection->initialize()
#1 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#2 /opt/lampp/htdocs/inventario/system/Session/Session.php(1027): session_start()
#3 /opt/lampp/htdocs/inventario/system/Session/Session.php(226): CodeIgniter\Session\Session->startSession()
#4 /opt/lampp/htdocs/inventario/system/Config/Services.php(714): CodeIgniter\Session\Session->start()
#5 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(100): CodeIgniter\Config\Services::session(Object(Config\App), false)
#6 /opt/lampp/htdocs/inventario/system/Config/Services.php(699): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#7 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(171): CodeIgniter\Config\Services::session()
#8 /opt/lampp/htdocs/inventario/system/Common.php(999): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 /opt/lampp/htdocs/inventario/app/Filters/AuthCheckFilter.php(13): session()
#10 /opt/lampp/htdocs/inventario/system/Filters/Filters.php(181): App\Filters\AuthCheckFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#11 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(403): CodeIgniter\Filters\Filters->run('/', 'before')
#12 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2021-10-14 12:45:21 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-10-14 12:45:21 --> Unable to connect to the database.
#0 /opt/lampp/htdocs/inventario/system/Session/Handlers/DatabaseHandler.php(115): CodeIgniter\Database\BaseConnection->initialize()
#1 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#2 /opt/lampp/htdocs/inventario/system/Session/Session.php(1027): session_start()
#3 /opt/lampp/htdocs/inventario/system/Session/Session.php(226): CodeIgniter\Session\Session->startSession()
#4 /opt/lampp/htdocs/inventario/system/Config/Services.php(714): CodeIgniter\Session\Session->start()
#5 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(100): CodeIgniter\Config\Services::session(Object(Config\App), false)
#6 /opt/lampp/htdocs/inventario/system/Config/Services.php(699): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#7 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(171): CodeIgniter\Config\Services::session()
#8 /opt/lampp/htdocs/inventario/system/Common.php(999): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 /opt/lampp/htdocs/inventario/app/Filters/AuthCheckFilter.php(13): session()
#10 /opt/lampp/htdocs/inventario/system/Filters/Filters.php(181): App\Filters\AuthCheckFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#11 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(403): CodeIgniter\Filters\Filters->run('/', 'before')
#12 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2021-10-14 12:46:18 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-10-14 12:46:18 --> Unable to connect to the database.
#0 /opt/lampp/htdocs/inventario/system/Session/Handlers/DatabaseHandler.php(115): CodeIgniter\Database\BaseConnection->initialize()
#1 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#2 /opt/lampp/htdocs/inventario/system/Session/Session.php(1027): session_start()
#3 /opt/lampp/htdocs/inventario/system/Session/Session.php(226): CodeIgniter\Session\Session->startSession()
#4 /opt/lampp/htdocs/inventario/system/Config/Services.php(714): CodeIgniter\Session\Session->start()
#5 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(100): CodeIgniter\Config\Services::session(Object(Config\App), false)
#6 /opt/lampp/htdocs/inventario/system/Config/Services.php(699): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#7 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(171): CodeIgniter\Config\Services::session()
#8 /opt/lampp/htdocs/inventario/system/Common.php(999): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 /opt/lampp/htdocs/inventario/app/Filters/AuthCheckFilter.php(13): session()
#10 /opt/lampp/htdocs/inventario/system/Filters/Filters.php(181): App\Filters\AuthCheckFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#11 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(403): CodeIgniter\Filters\Filters->run('/', 'before')
#12 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2021-10-14 12:46:41 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-10-14 12:46:41 --> Unable to connect to the database.
#0 /opt/lampp/htdocs/inventario/system/Session/Handlers/DatabaseHandler.php(115): CodeIgniter\Database\BaseConnection->initialize()
#1 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#2 /opt/lampp/htdocs/inventario/system/Session/Session.php(1027): session_start()
#3 /opt/lampp/htdocs/inventario/system/Session/Session.php(226): CodeIgniter\Session\Session->startSession()
#4 /opt/lampp/htdocs/inventario/system/Config/Services.php(714): CodeIgniter\Session\Session->start()
#5 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(100): CodeIgniter\Config\Services::session(Object(Config\App), false)
#6 /opt/lampp/htdocs/inventario/system/Config/Services.php(699): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#7 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(171): CodeIgniter\Config\Services::session()
#8 /opt/lampp/htdocs/inventario/system/Common.php(999): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 /opt/lampp/htdocs/inventario/app/Filters/LogadoFilter.php(13): session()
#10 /opt/lampp/htdocs/inventario/system/Filters/Filters.php(181): App\Filters\LogadoFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#11 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(403): CodeIgniter\Filters\Filters->run('/auth', 'before')
#12 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2021-10-14 12:54:12 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-10-14 12:54:12 --> Unable to connect to the database.
#0 /opt/lampp/htdocs/inventario/system/Session/Handlers/DatabaseHandler.php(115): CodeIgniter\Database\BaseConnection->initialize()
#1 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#2 /opt/lampp/htdocs/inventario/system/Session/Session.php(1027): session_start()
#3 /opt/lampp/htdocs/inventario/system/Session/Session.php(226): CodeIgniter\Session\Session->startSession()
#4 /opt/lampp/htdocs/inventario/system/Config/Services.php(714): CodeIgniter\Session\Session->start()
#5 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(100): CodeIgniter\Config\Services::session(Object(Config\App), false)
#6 /opt/lampp/htdocs/inventario/system/Config/Services.php(699): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#7 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(171): CodeIgniter\Config\Services::session()
#8 /opt/lampp/htdocs/inventario/system/Common.php(999): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 /opt/lampp/htdocs/inventario/app/Filters/AuthCheckFilter.php(13): session()
#10 /opt/lampp/htdocs/inventario/system/Filters/Filters.php(181): App\Filters\AuthCheckFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#11 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(403): CodeIgniter\Filters\Filters->run('/', 'before')
#12 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2021-10-14 12:54:18 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-10-14 12:54:18 --> Unable to connect to the database.
#0 /opt/lampp/htdocs/inventario/system/Session/Handlers/DatabaseHandler.php(115): CodeIgniter\Database\BaseConnection->initialize()
#1 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#2 /opt/lampp/htdocs/inventario/system/Session/Session.php(1027): session_start()
#3 /opt/lampp/htdocs/inventario/system/Session/Session.php(226): CodeIgniter\Session\Session->startSession()
#4 /opt/lampp/htdocs/inventario/system/Config/Services.php(714): CodeIgniter\Session\Session->start()
#5 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(100): CodeIgniter\Config\Services::session(Object(Config\App), false)
#6 /opt/lampp/htdocs/inventario/system/Config/Services.php(699): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#7 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(171): CodeIgniter\Config\Services::session()
#8 /opt/lampp/htdocs/inventario/system/Common.php(999): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 /opt/lampp/htdocs/inventario/app/Filters/AuthCheckFilter.php(13): session()
#10 /opt/lampp/htdocs/inventario/system/Filters/Filters.php(181): App\Filters\AuthCheckFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#11 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(403): CodeIgniter\Filters\Filters->run('/', 'before')
#12 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2021-10-14 12:54:18 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-10-14 12:54:18 --> Unable to connect to the database.
#0 /opt/lampp/htdocs/inventario/system/Session/Handlers/DatabaseHandler.php(115): CodeIgniter\Database\BaseConnection->initialize()
#1 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#2 /opt/lampp/htdocs/inventario/system/Session/Session.php(1027): session_start()
#3 /opt/lampp/htdocs/inventario/system/Session/Session.php(226): CodeIgniter\Session\Session->startSession()
#4 /opt/lampp/htdocs/inventario/system/Config/Services.php(714): CodeIgniter\Session\Session->start()
#5 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(100): CodeIgniter\Config\Services::session(Object(Config\App), false)
#6 /opt/lampp/htdocs/inventario/system/Config/Services.php(699): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#7 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(171): CodeIgniter\Config\Services::session()
#8 /opt/lampp/htdocs/inventario/system/Common.php(999): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 /opt/lampp/htdocs/inventario/app/Filters/AuthCheckFilter.php(13): session()
#10 /opt/lampp/htdocs/inventario/system/Filters/Filters.php(181): App\Filters\AuthCheckFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#11 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(403): CodeIgniter\Filters\Filters->run('/', 'before')
#12 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2021-10-14 12:54:19 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-10-14 12:54:19 --> Unable to connect to the database.
#0 /opt/lampp/htdocs/inventario/system/Session/Handlers/DatabaseHandler.php(115): CodeIgniter\Database\BaseConnection->initialize()
#1 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#2 /opt/lampp/htdocs/inventario/system/Session/Session.php(1027): session_start()
#3 /opt/lampp/htdocs/inventario/system/Session/Session.php(226): CodeIgniter\Session\Session->startSession()
#4 /opt/lampp/htdocs/inventario/system/Config/Services.php(714): CodeIgniter\Session\Session->start()
#5 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(100): CodeIgniter\Config\Services::session(Object(Config\App), false)
#6 /opt/lampp/htdocs/inventario/system/Config/Services.php(699): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#7 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(171): CodeIgniter\Config\Services::session()
#8 /opt/lampp/htdocs/inventario/system/Common.php(999): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 /opt/lampp/htdocs/inventario/app/Filters/AuthCheckFilter.php(13): session()
#10 /opt/lampp/htdocs/inventario/system/Filters/Filters.php(181): App\Filters\AuthCheckFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#11 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(403): CodeIgniter\Filters\Filters->run('/', 'before')
#12 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2021-10-14 12:54:19 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-10-14 12:54:19 --> Unable to connect to the database.
#0 /opt/lampp/htdocs/inventario/system/Session/Handlers/DatabaseHandler.php(115): CodeIgniter\Database\BaseConnection->initialize()
#1 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#2 /opt/lampp/htdocs/inventario/system/Session/Session.php(1027): session_start()
#3 /opt/lampp/htdocs/inventario/system/Session/Session.php(226): CodeIgniter\Session\Session->startSession()
#4 /opt/lampp/htdocs/inventario/system/Config/Services.php(714): CodeIgniter\Session\Session->start()
#5 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(100): CodeIgniter\Config\Services::session(Object(Config\App), false)
#6 /opt/lampp/htdocs/inventario/system/Config/Services.php(699): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#7 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(171): CodeIgniter\Config\Services::session()
#8 /opt/lampp/htdocs/inventario/system/Common.php(999): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 /opt/lampp/htdocs/inventario/app/Filters/AuthCheckFilter.php(13): session()
#10 /opt/lampp/htdocs/inventario/system/Filters/Filters.php(181): App\Filters\AuthCheckFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#11 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(403): CodeIgniter\Filters\Filters->run('/', 'before')
#12 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2021-10-14 12:54:19 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-10-14 12:54:19 --> Unable to connect to the database.
#0 /opt/lampp/htdocs/inventario/system/Session/Handlers/DatabaseHandler.php(115): CodeIgniter\Database\BaseConnection->initialize()
#1 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#2 /opt/lampp/htdocs/inventario/system/Session/Session.php(1027): session_start()
#3 /opt/lampp/htdocs/inventario/system/Session/Session.php(226): CodeIgniter\Session\Session->startSession()
#4 /opt/lampp/htdocs/inventario/system/Config/Services.php(714): CodeIgniter\Session\Session->start()
#5 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(100): CodeIgniter\Config\Services::session(Object(Config\App), false)
#6 /opt/lampp/htdocs/inventario/system/Config/Services.php(699): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#7 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(171): CodeIgniter\Config\Services::session()
#8 /opt/lampp/htdocs/inventario/system/Common.php(999): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 /opt/lampp/htdocs/inventario/app/Filters/AuthCheckFilter.php(13): session()
#10 /opt/lampp/htdocs/inventario/system/Filters/Filters.php(181): App\Filters\AuthCheckFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#11 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(403): CodeIgniter\Filters\Filters->run('/', 'before')
#12 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2021-10-14 12:54:19 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-10-14 12:54:19 --> Unable to connect to the database.
#0 /opt/lampp/htdocs/inventario/system/Session/Handlers/DatabaseHandler.php(115): CodeIgniter\Database\BaseConnection->initialize()
#1 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#2 /opt/lampp/htdocs/inventario/system/Session/Session.php(1027): session_start()
#3 /opt/lampp/htdocs/inventario/system/Session/Session.php(226): CodeIgniter\Session\Session->startSession()
#4 /opt/lampp/htdocs/inventario/system/Config/Services.php(714): CodeIgniter\Session\Session->start()
#5 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(100): CodeIgniter\Config\Services::session(Object(Config\App), false)
#6 /opt/lampp/htdocs/inventario/system/Config/Services.php(699): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#7 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(171): CodeIgniter\Config\Services::session()
#8 /opt/lampp/htdocs/inventario/system/Common.php(999): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 /opt/lampp/htdocs/inventario/app/Filters/AuthCheckFilter.php(13): session()
#10 /opt/lampp/htdocs/inventario/system/Filters/Filters.php(181): App\Filters\AuthCheckFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#11 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(403): CodeIgniter\Filters\Filters->run('/', 'before')
#12 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2021-10-14 12:54:48 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-10-14 12:54:48 --> Unable to connect to the database.
#0 /opt/lampp/htdocs/inventario/system/Session/Handlers/DatabaseHandler.php(115): CodeIgniter\Database\BaseConnection->initialize()
#1 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#2 /opt/lampp/htdocs/inventario/system/Session/Session.php(1027): session_start()
#3 /opt/lampp/htdocs/inventario/system/Session/Session.php(226): CodeIgniter\Session\Session->startSession()
#4 /opt/lampp/htdocs/inventario/system/Config/Services.php(714): CodeIgniter\Session\Session->start()
#5 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(100): CodeIgniter\Config\Services::session(Object(Config\App), false)
#6 /opt/lampp/htdocs/inventario/system/Config/Services.php(699): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#7 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(171): CodeIgniter\Config\Services::session()
#8 /opt/lampp/htdocs/inventario/system/Common.php(999): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 /opt/lampp/htdocs/inventario/app/Filters/AuthCheckFilter.php(13): session()
#10 /opt/lampp/htdocs/inventario/system/Filters/Filters.php(181): App\Filters\AuthCheckFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#11 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(403): CodeIgniter\Filters\Filters->run('/', 'before')
#12 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2021-10-14 12:54:49 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-10-14 12:54:49 --> Unable to connect to the database.
#0 /opt/lampp/htdocs/inventario/system/Session/Handlers/DatabaseHandler.php(115): CodeIgniter\Database\BaseConnection->initialize()
#1 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#2 /opt/lampp/htdocs/inventario/system/Session/Session.php(1027): session_start()
#3 /opt/lampp/htdocs/inventario/system/Session/Session.php(226): CodeIgniter\Session\Session->startSession()
#4 /opt/lampp/htdocs/inventario/system/Config/Services.php(714): CodeIgniter\Session\Session->start()
#5 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(100): CodeIgniter\Config\Services::session(Object(Config\App), false)
#6 /opt/lampp/htdocs/inventario/system/Config/Services.php(699): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#7 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(171): CodeIgniter\Config\Services::session()
#8 /opt/lampp/htdocs/inventario/system/Common.php(999): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 /opt/lampp/htdocs/inventario/app/Filters/AuthCheckFilter.php(13): session()
#10 /opt/lampp/htdocs/inventario/system/Filters/Filters.php(181): App\Filters\AuthCheckFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#11 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(403): CodeIgniter\Filters\Filters->run('/', 'before')
#12 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2021-10-14 12:55:33 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-10-14 12:55:33 --> Unable to connect to the database.
#0 /opt/lampp/htdocs/inventario/system/Session/Handlers/DatabaseHandler.php(115): CodeIgniter\Database\BaseConnection->initialize()
#1 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#2 /opt/lampp/htdocs/inventario/system/Session/Session.php(1027): session_start()
#3 /opt/lampp/htdocs/inventario/system/Session/Session.php(226): CodeIgniter\Session\Session->startSession()
#4 /opt/lampp/htdocs/inventario/system/Config/Services.php(714): CodeIgniter\Session\Session->start()
#5 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(100): CodeIgniter\Config\Services::session(Object(Config\App), false)
#6 /opt/lampp/htdocs/inventario/system/Config/Services.php(699): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#7 /opt/lampp/htdocs/inventario/system/Config/BaseService.php(171): CodeIgniter\Config\Services::session()
#8 /opt/lampp/htdocs/inventario/system/Common.php(999): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 /opt/lampp/htdocs/inventario/app/Filters/AuthCheckFilter.php(13): session()
#10 /opt/lampp/htdocs/inventario/system/Filters/Filters.php(181): App\Filters\AuthCheckFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#11 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(403): CodeIgniter\Filters\Filters->run('/', 'before')
#12 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2021-10-14 13:35:35 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ANDprateleira =  "" ANDestante = ANDcaixa =  "" ANDcod =  ""' at line 1 in /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT * FROM p...')
#1 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM p...')
#2 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM p...')
#3 /opt/lampp/htdocs/inventario/app/Controllers/Crud.php(294): CodeIgniter\Database\BaseConnection->query('SELECT * FROM p...')
#4 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(937): App\Controllers\Crud->search_single_data()
#5 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#6 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2021-10-14 13:35:40 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ANDprateleira =  "" ANDestante = ANDcaixa =  "" ANDcod =  ""' at line 1 in /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT * FROM p...')
#1 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM p...')
#2 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM p...')
#3 /opt/lampp/htdocs/inventario/app/Controllers/Crud.php(294): CodeIgniter\Database\BaseConnection->query('SELECT * FROM p...')
#4 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(937): App\Controllers\Crud->search_single_data()
#5 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#6 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2021-10-14 13:35:48 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ANDprateleira =  "" ANDestante = ANDcaixa =  "" ANDcod =  ""' at line 1 in /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT * FROM p...')
#1 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM p...')
#2 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM p...')
#3 /opt/lampp/htdocs/inventario/app/Controllers/Crud.php(294): CodeIgniter\Database\BaseConnection->query('SELECT * FROM p...')
#4 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(937): App\Controllers\Crud->search_single_data()
#5 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#6 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2021-10-14 13:35:52 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ANDprateleira =  "" ANDestante = ANDcaixa =  "" ANDcod =  ""' at line 1 in /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT * FROM p...')
#1 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM p...')
#2 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM p...')
#3 /opt/lampp/htdocs/inventario/app/Controllers/Crud.php(294): CodeIgniter\Database\BaseConnection->query('SELECT * FROM p...')
#4 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(937): App\Controllers\Crud->search_single_data()
#5 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#6 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2021-10-14 13:36:32 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ANDprateleira =  "" ANDestante = ANDcaixa =  "" ANDcod =  ""' at line 1 in /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT * FROM p...')
#1 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM p...')
#2 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM p...')
#3 /opt/lampp/htdocs/inventario/app/Controllers/Crud.php(280): CodeIgniter\Database\BaseConnection->query('SELECT * FROM p...')
#4 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(937): App\Controllers\Crud->search_single_data()
#5 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#6 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2021-10-14 13:36:41 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ANDprateleira =  "" ANDestante = ANDcaixa =  "" ANDcod =  ""' at line 1 in /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT * FROM p...')
#1 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM p...')
#2 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM p...')
#3 /opt/lampp/htdocs/inventario/app/Controllers/Crud.php(280): CodeIgniter\Database\BaseConnection->query('SELECT * FROM p...')
#4 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(937): App\Controllers\Crud->search_single_data()
#5 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#6 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2021-10-14 13:37:03 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ANDprateleira =  "" ANDestante =  "" ANDcaixa =  "" ANDcod = AND' at line 1 in /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT * FROM p...')
#1 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM p...')
#2 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM p...')
#3 /opt/lampp/htdocs/inventario/app/Controllers/Crud.php(280): CodeIgniter\Database\BaseConnection->query('SELECT * FROM p...')
#4 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(937): App\Controllers\Crud->search_single_data()
#5 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#6 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2021-10-14 13:38:45 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ANDprateleira =  "" ANDestante = ANDcaixa =  "" ANDcod =  ""' at line 1 in /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT * FROM p...')
#1 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM p...')
#2 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM p...')
#3 /opt/lampp/htdocs/inventario/app/Controllers/Crud.php(280): CodeIgniter\Database\BaseConnection->query('SELECT * FROM p...')
#4 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(937): App\Controllers\Crud->search_single_data()
#5 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#6 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2021-10-14 13:39:21 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND caixa =  "" AND cod =  ""' at line 1 in /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT * FROM p...')
#1 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM p...')
#2 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM p...')
#3 /opt/lampp/htdocs/inventario/app/Controllers/Crud.php(280): CodeIgniter\Database\BaseConnection->query('SELECT * FROM p...')
#4 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(937): App\Controllers\Crud->search_single_data()
#5 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#6 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2021-10-14 13:40:14 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'caixa =  "" AND cod =  ""' at line 1 in /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT * FROM p...')
#1 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM p...')
#2 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM p...')
#3 /opt/lampp/htdocs/inventario/app/Controllers/Crud.php(280): CodeIgniter\Database\BaseConnection->query('SELECT * FROM p...')
#4 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(937): App\Controllers\Crud->search_single_data()
#5 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#6 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2021-10-14 13:40:36 --> mysqli_sql_exception: Unknown column 'cod' in 'where clause' in /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT * FROM p...')
#1 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM p...')
#2 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM p...')
#3 /opt/lampp/htdocs/inventario/app/Controllers/Crud.php(280): CodeIgniter\Database\BaseConnection->query('SELECT * FROM p...')
#4 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(937): App\Controllers\Crud->search_single_data()
#5 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#6 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2021-10-14 13:42:32 --> mysqli_sql_exception: Unknown column 'cod' in 'where clause' in /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT * FROM p...')
#1 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM p...')
#2 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM p...')
#3 /opt/lampp/htdocs/inventario/app/Controllers/Crud.php(280): CodeIgniter\Database\BaseConnection->query('SELECT * FROM p...')
#4 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(937): App\Controllers\Crud->search_single_data()
#5 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#6 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2021-10-14 13:42:47 --> mysqli_sql_exception: Unknown column 'cod' in 'where clause' in /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT * FROM p...')
#1 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM p...')
#2 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM p...')
#3 /opt/lampp/htdocs/inventario/app/Controllers/Crud.php(280): CodeIgniter\Database\BaseConnection->query('SELECT * FROM p...')
#4 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(937): App\Controllers\Crud->search_single_data()
#5 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#6 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2021-10-14 13:44:23 --> mysqli_sql_exception: Unknown column 'cod' in 'where clause' in /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT * FROM p...')
#1 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM p...')
#2 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM p...')
#3 /opt/lampp/htdocs/inventario/app/Controllers/Crud.php(280): CodeIgniter\Database\BaseConnection->query('SELECT * FROM p...')
#4 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(937): App\Controllers\Crud->search_single_data()
#5 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#6 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-10-14 13:49:40 --> syntax error, unexpected end of file
#0 /opt/lampp/htdocs/inventario/system/Autoloader/Autoloader.php(265): CodeIgniter\Autoloader\Autoloader->includeFile('/opt/lampp/htdo...')
#1 /opt/lampp/htdocs/inventario/system/Autoloader/Autoloader.php(228): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(894): class_exists('\\App\\Controller...', true)
#5 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(417): CodeIgniter\CodeIgniter->startController()
#6 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2021-10-14 13:50:02 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND estante = 05' at line 1 in /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT * FROM p...')
#1 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM p...')
#2 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM p...')
#3 /opt/lampp/htdocs/inventario/app/Controllers/Crud.php(276): CodeIgniter\Database\BaseConnection->query('SELECT * FROM p...')
#4 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(937): App\Controllers\Crud->search_single_data()
#5 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#6 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2021-10-14 13:52:18 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1 in /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT * FROM p...')
#1 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM p...')
#2 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM p...')
#3 /opt/lampp/htdocs/inventario/app/Controllers/Crud.php(276): CodeIgniter\Database\BaseConnection->query('SELECT * FROM p...')
#4 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(937): App\Controllers\Crud->search_single_data()
#5 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#6 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-10-14 14:06:25 --> Call to undefined method CodeIgniter\Database\MySQLi\Result::num_fields()
#0 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(937): App\Controllers\Crud->search_single_data()
#1 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#2 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-10-14 14:09:32 --> Call to a member function query() on null
#0 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(937): App\Controllers\Crud->search_single_data()
#1 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#2 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#4 {main}
ERROR - 2021-10-14 14:15:57 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1 in /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT * FROM p...')
#1 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM p...')
#2 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM p...')
#3 /opt/lampp/htdocs/inventario/app/Controllers/Crud.php(290): CodeIgniter\Database\BaseConnection->query('SELECT * FROM p...')
#4 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(937): App\Controllers\Crud->search_single_data()
#5 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#6 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2021-10-14 14:15:58 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1 in /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT * FROM p...')
#1 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM p...')
#2 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM p...')
#3 /opt/lampp/htdocs/inventario/app/Controllers/Crud.php(290): CodeIgniter\Database\BaseConnection->query('SELECT * FROM p...')
#4 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(937): App\Controllers\Crud->search_single_data()
#5 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#6 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2021-10-14 14:15:58 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1 in /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT * FROM p...')
#1 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM p...')
#2 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM p...')
#3 /opt/lampp/htdocs/inventario/app/Controllers/Crud.php(290): CodeIgniter\Database\BaseConnection->query('SELECT * FROM p...')
#4 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(937): App\Controllers\Crud->search_single_data()
#5 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#6 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-10-14 14:16:57 --> The HTML code size is larger than pcre.backtrack_limit 1000000. You should use WriteHTML() with smaller string lengths.
#0 /opt/lampp/htdocs/inventario/vendor/mpdf/mpdf/src/Mpdf.php(13296): Mpdf\Mpdf->AdjustHTML('\n        \n     ...', 8)
#1 /opt/lampp/htdocs/inventario/app/Controllers/Relatorio.php(68): Mpdf\Mpdf->WriteHTML('\n        \n     ...')
#2 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(937): App\Controllers\Relatorio->printpdf_processos()
#3 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Relatorio))
#4 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
ERROR - 2021-10-14 14:17:08 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND estante =  AND caixa =  AND cod_inventario =' at line 1 in /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT * FROM p...')
#1 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM p...')
#2 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM p...')
#3 /opt/lampp/htdocs/inventario/app/Controllers/Crud.php(290): CodeIgniter\Database\BaseConnection->query('SELECT * FROM p...')
#4 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(937): App\Controllers\Crud->search_single_data()
#5 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#6 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2021-10-14 16:00:44 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1 in /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT * FROM p...')
#1 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM p...')
#2 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM p...')
#3 /opt/lampp/htdocs/inventario/app/Controllers/Crud.php(290): CodeIgniter\Database\BaseConnection->query('SELECT * FROM p...')
#4 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(937): App\Controllers\Crud->search_single_data()
#5 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#6 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-10-14 16:00:44 --> Return value of CodeIgniter\Database\MySQLi\Result::getNumRows() must be of the type int, null returned
#0 /opt/lampp/htdocs/inventario/app/Controllers/Crud.php(294): CodeIgniter\Database\MySQLi\Result->getNumRows()
#1 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(937): App\Controllers\Crud->search_single_data()
#2 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#3 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#5 {main}
ERROR - 2021-10-14 16:01:13 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1 in /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT * FROM p...')
#1 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM p...')
#2 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM p...')
#3 /opt/lampp/htdocs/inventario/app/Controllers/Crud.php(290): CodeIgniter\Database\BaseConnection->query('SELECT * FROM p...')
#4 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(937): App\Controllers\Crud->search_single_data()
#5 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#6 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2021-10-14 16:03:11 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1 in /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT * FROM p...')
#1 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM p...')
#2 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM p...')
#3 /opt/lampp/htdocs/inventario/app/Controllers/Crud.php(290): CodeIgniter\Database\BaseConnection->query('SELECT * FROM p...')
#4 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(937): App\Controllers\Crud->search_single_data()
#5 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#6 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2021-10-14 16:03:12 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1 in /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT * FROM p...')
#1 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM p...')
#2 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM p...')
#3 /opt/lampp/htdocs/inventario/app/Controllers/Crud.php(290): CodeIgniter\Database\BaseConnection->query('SELECT * FROM p...')
#4 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(937): App\Controllers\Crud->search_single_data()
#5 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#6 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2021-10-14 16:03:12 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1 in /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT * FROM p...')
#1 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM p...')
#2 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM p...')
#3 /opt/lampp/htdocs/inventario/app/Controllers/Crud.php(290): CodeIgniter\Database\BaseConnection->query('SELECT * FROM p...')
#4 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(937): App\Controllers\Crud->search_single_data()
#5 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#6 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2021-10-14 16:03:24 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1 in /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT * FROM p...')
#1 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM p...')
#2 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM p...')
#3 /opt/lampp/htdocs/inventario/app/Controllers/Crud.php(290): CodeIgniter\Database\BaseConnection->query('SELECT * FROM p...')
#4 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(937): App\Controllers\Crud->search_single_data()
#5 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#6 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2021-10-14 16:03:26 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1 in /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT * FROM p...')
#1 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM p...')
#2 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM p...')
#3 /opt/lampp/htdocs/inventario/app/Controllers/Crud.php(290): CodeIgniter\Database\BaseConnection->query('SELECT * FROM p...')
#4 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(937): App\Controllers\Crud->search_single_data()
#5 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#6 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2021-10-14 20:48:18 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1 in /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /opt/lampp/htdocs/inventario/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT * FROM p...')
#1 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM p...')
#2 /opt/lampp/htdocs/inventario/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM p...')
#3 /opt/lampp/htdocs/inventario/app/Controllers/Crud.php(290): CodeIgniter\Database\BaseConnection->query('SELECT * FROM p...')
#4 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(937): App\Controllers\Crud->search_single_data()
#5 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#6 /opt/lampp/htdocs/inventario/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /opt/lampp/htdocs/inventario/index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
